package com.urbondo.user.service.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "urbondo-user")
public record UserEntity(@DynamoDBHashKey @DynamoDBAutoGeneratedKey String id,
                         @DynamoDBAttribute String firstName,
                         @DynamoDBAttribute String lastName,
                         @DynamoDBAttribute String email,
                         @DynamoDBAttribute String phone) {}
